# Generated by Django 4.2.4 on 2023-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='date_published',
            field=models.DateField(auto_now=True),
        ),
    ]
