# Generated by Django 4.2.4 on 2023-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobvacancy_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
